# Generated by Django 6.0.1 on 2026-01-11 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='タイトル')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
                ('prompt', models.TextField(verbose_name='プロンプト')),
                ('negative_prompt', models.TextField(blank=True, verbose_name='ネガティブプロンプト')),
                ('ai_model', models.CharField(choices=[('DaysAI', 'DaysAI'), ('nanobanana', 'nanobanana')], max_length=50, verbose_name='AIモデル')),
                ('category', models.CharField(choices=[('Image Generation', '画像生成'), ('Image Correction', '画像修正')], max_length=50, verbose_name='カテゴリー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.post', verbose_name='投稿')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント一覧',
                'ordering': ['created_at'],
            },
        ),
    ]
